name: "Test, package, lint"

on:
  push:
  pull_request:

jobs:
  test:
    name: "Test on Python ${{ matrix.nox-unit }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nox-unit: [2.7, 3.4, 3.5, 3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # this is only for running Nox itself

      - name: Install dependencies
        run: python -m pip install -U pip wheel nox

      - name: Test with nox
        run: NOXSESSION="unit-${{ matrix.nox-unit }}" nox

  package:
    name: "Package for Python ${{ matrix.python-version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install -U pip wheel

      - name: Package wheel
        run: python setup.py bdist_wheel

  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: python -m pip install -U pip wheel nox

      - name: Lint
        run: NOXSESSION=lint nox
