name: "Test, package, lint"

on:
  push:
  pull_request:

jobs:
  test:
    name: "Test ${{ matrix.os }} / Python ${{ matrix.nox-unit }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        nox-unit: [2.7, 3.4, 3.5, 3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # this is only for running Nox itself

      - name: Install dependencies
        run: python -m pip install -U pip wheel nox

      - name: Test with nox
        run: nox
        env:
          NOXSESSION: "unit-${{ matrix.nox-unit }}"

  test-windows:
    name: "Test windows-latest / Python ${{ matrix.python-version }}"
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        # nox does not work with 2.7 and windows runner doesn't know about 3.4.
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}  # this is only for running Nox itself

      - name: Install dependencies
        run: python -m pip install -U pip wheel nox

      - name: Test with nox
        run: nox
        env:
          NOXSESSION: "unit-${{ matrix.python-version }}"

  package:
    name: "Package for Python ${{ matrix.python-version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install -U pip wheel

      - name: Package wheel
        run: python setup.py bdist_wheel

      - uses: actions/upload-artifact@v2
        with:
          path: dist/cmarkgfm-*.whl

  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: python -m pip install -U pip wheel nox

      - name: Lint
        run: NOXSESSION=lint nox
